---
name: "Publish package to the Maven Central Repository"
"on":
  release:
    types:
    - "created"
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      packages: "write"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Set up Maven Central Repository"
      uses: "actions/setup-java@v4"
      with:
        java-version: "23"
        distribution: "temurin"
        server-id: "central"
        server-username: "CENTRAL_TOKEN_USERNAME"
        server-password: "CENTRAL_TOKEN_PASSWORD"
        gpg-private-key: "GPG_SIGNING_KEY"
        gpg-passphrase: "GPG_SIGNING_KEY_PASSWORD"
    - name: "Build with Maven"
      run: "mvn -B package --file pom.xml"
    - name: "Publish package"
      run: "mvn -P release --batch-mode deploy -DskipTests"
      env:
        CENTRAL_TOKEN_USERNAME: "${{ secrets.CENTRAL_TOKEN_USERNAME }}"
        CENTRAL_TOKEN_PASSWORD: "${{ secrets.CENTRAL_TOKEN_PASSWORD }}"
        GPG_SIGNING_KEY: "${{ secrets.GPG_SIGNING_KEY }}"
        GPG_SIGNING_KEY_PASSWORD: "${{ secrets.GPG_SIGNING_KEY_PASSWORD }}"
